/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generateFromForm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["metadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GenerateRequest: {
            /** Format: int32 */
            schemaVersion?: number;
            projectName?: string;
            options?: {
                [key: string]: unknown;
            };
            variables?: {
                [key: string]: string;
            };
        };
        Diagnostic: {
            code?: string;
            stage?: string;
            optionId?: string;
            recipe?: string;
            message?: string;
            hint?: string;
        };
        ResolvedRecipe: {
            id?: string;
            label?: string;
            kind?: string;
            recipeVersion?: string;
            frameworkVersion?: string;
            implied?: boolean;
        };
        ValidationResponse: {
            valid?: boolean;
            catalogDigest?: string;
            selectionHash?: string;
            recipes?: components["schemas"]["ResolvedRecipe"][];
            capabilities?: string[];
            effectiveOptions?: {
                [key: string]: unknown;
            };
            conflicts?: components["schemas"]["Diagnostic"][];
            warnings?: components["schemas"]["Diagnostic"][];
        };
        Choice: {
            value?: string;
            label?: string;
            recipeId?: string;
            recipeVersion?: string;
            frameworkVersion?: string;
            provides?: string[];
            requires?: string[];
            conflictsWith?: string[];
            verification?: string;
        };
        Group: {
            id?: string;
            label?: string;
            help?: string;
            /** Format: int32 */
            order?: number;
            options?: components["schemas"]["Option"][];
        };
        MetadataDocument: {
            /** Format: int32 */
            schemaVersion?: number;
            catalogDigest?: string;
            /** Format: int32 */
            recipeCount?: number;
            groups?: components["schemas"]["Group"][];
            variables?: components["schemas"]["Variable"][];
            recipes?: components["schemas"]["RecipeSummary"][];
        };
        Option: {
            id?: string;
            type?: string;
            label?: string;
            help?: string;
            required?: boolean;
            defaultValue?: unknown;
            availableWhen?: string;
            choices?: components["schemas"]["Choice"][];
        };
        RecipeSummary: {
            id?: string;
            label?: string;
            kind?: string;
            slot?: string;
            recipeVersion?: string;
            frameworkVersion?: string;
            provides?: string[];
            requires?: string[];
            conflictsWith?: string[];
        };
        Variable: {
            id?: string;
            label?: string;
            help?: string;
            pattern?: string;
            defaultValue?: string;
            scope?: string;
            requiredBy?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    validate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ValidationResponse"];
                };
            };
        };
    };
    generateFromForm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    selection: string;
                };
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    metadata: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MetadataDocument"];
                };
            };
        };
    };
}
