/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/presets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["read"];
        put: operations["update"];
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presets/{id}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generations/{id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["replay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generations/{id}/keep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["keep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generations/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["download"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generateFromForm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["metadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["read_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generations/{id}/diff/{otherId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["diff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GenerateRequest: {
            /** Format: int32 */
            schemaVersion?: number;
            projectName?: string;
            options?: {
                [key: string]: unknown;
            };
            variables?: {
                [key: string]: string;
            };
        };
        PresetRequest: {
            name?: string;
            description?: string;
            visibility?: string;
            selection?: components["schemas"]["GenerateRequest"];
            versionPolicy?: string;
            pinnedRecipes?: {
                [key: string]: string;
            };
        };
        PresetResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            description?: string;
            visibility?: string;
            selection?: components["schemas"]["GenerateRequest"];
            versionPolicy?: string;
            pinnedRecipes?: {
                [key: string]: string;
            };
            /** Format: int32 */
            revision?: number;
            mine?: boolean;
            recipeIds?: string[];
            staleReason?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Diagnostic: {
            code?: string;
            stage?: string;
            optionId?: string;
            recipe?: string;
            message?: string;
            hint?: string;
        };
        ResolvedRecipe: {
            id?: string;
            label?: string;
            kind?: string;
            recipeVersion?: string;
            frameworkVersion?: string;
            implied?: boolean;
        };
        ValidationResponse: {
            valid?: boolean;
            catalogDigest?: string;
            selectionHash?: string;
            recipes?: components["schemas"]["ResolvedRecipe"][];
            capabilities?: string[];
            effectiveOptions?: {
                [key: string]: unknown;
            };
            conflicts?: components["schemas"]["Diagnostic"][];
            warnings?: components["schemas"]["Diagnostic"][];
        };
        ReplayResponse: {
            mode?: string;
            originalCatalogDigest?: string;
            currentCatalogDigest?: string;
            catalogMoved?: boolean;
            summary?: string;
            changes?: components["schemas"]["VersionChange"][];
        };
        VersionChange: {
            recipeId?: string;
            before?: string;
            after?: string;
        };
        GenerationResponse: {
            /** Format: uuid */
            id?: string;
            projectName?: string;
            selection?: components["schemas"]["GenerateRequest"];
            lock?: {
                [key: string]: string;
            };
            catalogDigest?: string;
            selectionHash?: string;
            status?: string;
            /** Format: int32 */
            durationMillis?: number;
            /** Format: int32 */
            sizeBytes?: number;
            kept?: boolean;
            exactlyReproducible?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            expiresAt?: string;
        };
        Choice: {
            value?: string;
            label?: string;
            recipeId?: string;
            recipeVersion?: string;
            frameworkVersion?: string;
            provides?: string[];
            requires?: string[];
            conflictsWith?: string[];
            verification?: string;
        };
        Group: {
            id?: string;
            label?: string;
            help?: string;
            /** Format: int32 */
            order?: number;
            options?: components["schemas"]["Option"][];
        };
        MetadataDocument: {
            /** Format: int32 */
            schemaVersion?: number;
            catalogDigest?: string;
            /** Format: int32 */
            recipeCount?: number;
            groups?: components["schemas"]["Group"][];
            variables?: components["schemas"]["Variable"][];
            recipes?: components["schemas"]["RecipeSummary"][];
        };
        Option: {
            id?: string;
            type?: string;
            label?: string;
            help?: string;
            required?: boolean;
            defaultValue?: unknown;
            availableWhen?: string;
            choices?: components["schemas"]["Choice"][];
        };
        RecipeSummary: {
            id?: string;
            label?: string;
            kind?: string;
            slot?: string;
            recipeVersion?: string;
            frameworkVersion?: string;
            provides?: string[];
            requires?: string[];
            conflictsWith?: string[];
        };
        Variable: {
            id?: string;
            label?: string;
            help?: string;
            pattern?: string;
            defaultValue?: string;
            scope?: string;
            requiredBy?: string[];
        };
        LockDiff: {
            changed?: components["schemas"]["VersionChange"][];
            added?: components["schemas"]["VersionChange"][];
            removed?: components["schemas"]["VersionChange"][];
            empty?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PresetResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresetRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PresetResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    validate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ValidationResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PresetResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresetRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PresetResponse"];
                };
            };
        };
    };
    generate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    replay: {
        parameters: {
            query?: {
                mode?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReplayResponse"];
                };
            };
        };
    };
    keep: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GenerationResponse"];
                };
            };
        };
    };
    download: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    generateFromForm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    selection: string;
                };
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    metadata: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MetadataDocument"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GenerationResponse"][];
                };
            };
        };
    };
    read_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GenerationResponse"];
                };
            };
        };
    };
    diff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                otherId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LockDiff"];
                };
            };
        };
    };
}
