package dev.kitbash.render;

import dev.kitbash.core.patch.PatchOp;
import dev.kitbash.core.pipeline.GenerationPipeline;
import dev.kitbash.core.plan.RecipeContent;
import dev.kitbash.core.recipe.Capability;
import dev.kitbash.core.recipe.Catalog;
import dev.kitbash.core.recipe.FileRule;
import dev.kitbash.core.recipe.OptionSpec;
import dev.kitbash.core.recipe.OptionType;
import dev.kitbash.core.recipe.PatchRule;
import dev.kitbash.core.recipe.Recipe;
import dev.kitbash.core.recipe.RecipeId;
import dev.kitbash.core.recipe.RecipeKind;
import dev.kitbash.core.recipe.RecipeVersion;
import dev.kitbash.core.selection.OptionValue;
import dev.kitbash.core.selection.SelectionEnvelope;
import java.nio.charset.StandardCharsets;
import java.nio.file.FileSystems;
import java.nio.file.Path;
import java.nio.file.PathMatcher;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * A two-recipe catalog wired to the <b>real</b> Pebble render stage.
 *
 * <p>The pipeline tests in {@code core} use a substitution stub, because the seam exists so the
 * other six stages can be tested without a template engine. This fixture exists for the one
 * question that needs the whole stack: are the bytes identical across two JVM invocations?
 */
final class PipelineFixture {

    static final RecipeId BASE = RecipeId.of("base");
    static final RecipeId BACKEND = RecipeId.of("backend-spring-java");

    private PipelineFixture() {}

    static GenerationPipeline pipeline() {
        return GenerationPipeline.over(catalog(), content(), new PebbleRenderStage());
    }

    static SelectionEnvelope selection(String projectName) {
        return SelectionEnvelope.current(
                projectName,
                Map.of("backend", "backend-spring-java", "architecture", "layered"),
                Map.of("groupId", "com.acme", "packageName", "com.acme.customer", "javaVersion", "21"));
    }

    static Catalog catalog() {
        return Catalog.of(List.of(base(), backend()), "sha256:fixture");
    }

    private static Recipe base() {
        return new Recipe(
                BASE,
                RecipeVersion.parse("1.0.0"),
                null,
                RecipeKind.BASE,
                "Project skeleton",
                Set.of(Capability.of("project-root")),
                Set.of(),
                Set.of(),
                List.of(),
                Set.of(),
                List.of(FileRule.always("files/**")),
                List.of(),
                false);
    }

    private static Recipe backend() {
        return new Recipe(
                BACKEND,
                RecipeVersion.parse("1.4.0"),
                "3.5.5",
                RecipeKind.BACKEND,
                "Spring Boot (Java)",
                Set.of(Capability.of("rest-api"), Capability.of("jvm-project")),
                Set.of(Capability.of("project-root")),
                Set.of(),
                List.of(new OptionSpec(
                        "architecture",
                        OptionType.ENUM,
                        List.of("layered", "hexagonal"),
                        OptionValue.text("layered"),
                        "Architecture",
                        "Determines the package layout and dependency direction.")),
                Set.of("groupId", "packageName"),
                List.of(FileRule.always("files/**"), new FileRule("arch/layered/**", "architecture == 'layered'")),
                List.of(
                        PatchRule.always(new PatchOp.AppendLines(BACKEND, ".gitignore", List.of("build/", ".gradle/"))),
                        PatchRule.always(new PatchOp.MergeYaml(
                                BACKEND,
                                "src/main/resources/application.yaml",
                                Map.of("spring", Map.of("application", Map.of("name", "generated")))))),
                false);
    }

    static RecipeContent content() {
        Map<RecipeId, Map<String, String>> trees = new LinkedHashMap<>();
        Map<String, String> baseFiles = new LinkedHashMap<>();
        baseFiles.put("files/README.md.peb", "# {{ projectName }}\n\nGroup: {{ groupId }}\n");
        baseFiles.put("files/.gitignore", "# generated by kitbash\n");
        trees.put(BASE, baseFiles);

        Map<String, String> backendFiles = new LinkedHashMap<>();
        backendFiles.put(
                "files/build.gradle.kts.peb",
                "group = \"{{ groupId }}\"\n\njava {\n    toolchain { languageVersion = JavaLanguageVersion.of({{ javaVersion }}) }\n}\n");
        backendFiles.put("files/src/main/resources/application.yaml", "server:\n  port: 8080\n");
        backendFiles.put(
                "arch/layered/src/main/java/{{ packageName | packagePath }}/web/CustomerController.java.peb",
                "package {{ packageName }}.web;\n\npublic class {{ projectName | pascal }}Controller {}\n");
        trees.put(BACKEND, backendFiles);
        return new MapRecipeContent(trees);
    }

    private record MapRecipeContent(Map<RecipeId, Map<String, String>> trees) implements RecipeContent {

        @Override
        public List<RecipeFile> filesMatching(RecipeId recipeId, String glob) {
            PathMatcher matcher = FileSystems.getDefault().getPathMatcher("glob:" + glob);
            List<RecipeFile> files = new ArrayList<>();
            trees.getOrDefault(recipeId, Map.of()).entrySet().stream()
                    .filter(entry -> matcher.matches(Path.of(entry.getKey())))
                    .sorted(Map.Entry.comparingByKey())
                    .forEach(entry -> {
                        byte[] bytes = entry.getValue().getBytes(StandardCharsets.UTF_8);
                        files.add(new RecipeFile(entry.getKey(), () -> bytes, false, bytes.length));
                    });
            return files;
        }
    }
}
