#!/bin/bash
#
# Copies the read-only project into a writable workspace and runs the build.
set -euo pipefail

# Copied only into an empty workspace. A cell whose steps share a volume (§33's typed client is
# generated by one ecosystem and consumed by the other) would otherwise have its second step
# overwrite everything the first one produced with the original, unbuilt project.
if [ -z "$(ls -A /workspace 2>/dev/null)" ]; then
  cp -a /input/. /workspace/
fi

# A cell names the directory its commands run in. For the JVM half that is always the
# project root today, and saying so explicitly keeps one cell shape covering both images.
if [ -n "${KITBASH_WORKING_DIRECTORY:-}" ]; then
  cd "/workspace/${KITBASH_WORKING_DIRECTORY}"
fi

# docker-java — which Testcontainers uses — defaults to Docker API v1.32, and
# daemons from Docker 29 onward refuse it outright ("Could not find a valid Docker
# environment"). The runner passes the daemon's own advertised version, which every
# daemon accepts by definition, so this works on old and new hosts alike.
#
# It goes in ~/.docker-java.properties rather than an environment variable because
# that file is the only one of the three sources docker-java reads that survives
# the fork into Gradle's test JVM.
if [ -n "${KITBASH_DOCKER_API_VERSION:-}" ]; then
  echo "api.version=${KITBASH_DOCKER_API_VERSION}" > "$HOME/.docker-java.properties"
fi

exec "$@"
