package dev.kitbash.core.git;

import dev.kitbash.core.workspace.GeneratedFile;
import dev.kitbash.core.workspace.Workspace;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HexFormat;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.zip.Deflater;

/**
 * Writes an initialised {@code .git} directory, with the generated project already committed, into
 * the workspace itself.
 *
 * <p>The point is that unzipping gives a repository rather than a pile of files: {@code git log}
 * shows one commit, {@code git status} is clean, and the user's first commit is their own work
 * rather than "add everything".
 *
 * <p>Everything is fixed — author, committer, timestamp, timezone, message — because the zip is
 * required to be byte-identical for identical input (§4), and a commit carries two timestamps that
 * would otherwise make every generation unique. The consequence is that two people generating the
 * same project get the same commit hash, which is the intended property.
 *
 * <p>Objects are written by hand rather than through a git library: {@code core} depends on the JDK
 * and nothing else (§5), and the loose-object format is a header, a SHA-1 and zlib.
 */
public final class GitSkeletonWriter {

    public static final String AUTHOR_NAME = "kitbash";
    public static final String AUTHOR_EMAIL = "noreply@kitbash.dev";

    /** 2020-01-01T00:00:00Z. A fixed instant, chosen once, never "now". */
    public static final long COMMIT_EPOCH_SECONDS = 1_577_836_800L;

    public static final String TIMEZONE = "+0000";
    public static final String BRANCH = "main";

    private static final int REGULAR_FILE_MODE = 0_100644;
    private static final int EXECUTABLE_FILE_MODE = 0_100755;
    private static final int DIRECTORY_MODE = 0_040000;

    private GitSkeletonWriter() {}

    /**
     * Adds {@code .git} to {@code workspace}, committing every file already in it.
     *
     * @param commitMessage the single commit's message
     * @return the commit's SHA-1, for callers that want to log or assert on it
     */
    public static String write(Workspace workspace, String commitMessage) {
        Map<String, GeneratedFile> files = new TreeMap<>(workspace.files());
        if (files.isEmpty()) {
            throw new IllegalArgumentException("refusing to commit an empty workspace");
        }

        ObjectStore objects = new ObjectStore();
        Map<String, String> blobIds = new TreeMap<>();
        for (Map.Entry<String, GeneratedFile> file : files.entrySet()) {
            blobIds.put(file.getKey(), objects.write("blob", file.getValue().content()));
        }

        String treeId = writeTree(objects, files, blobIds, "");
        String commitId = objects.write("commit", commitObject(treeId, commitMessage));

        objects.entries().forEach((path, content) -> workspace.put(path, GeneratedFile.of(content)));

        workspace.putText(".git/HEAD", "ref: refs/heads/" + BRANCH + "\n");
        workspace.putText(".git/refs/heads/" + BRANCH, commitId + "\n");
        workspace.putText(".git/config", config());
        workspace.putText(".git/description", "Generated by kitbash.\n");
        workspace.put(".git/index", GeneratedFile.of(index(files, blobIds)));

        return commitId;
    }

    /**
     * Writes the tree for one directory, recursing into its subdirectories first.
     *
     * <p>Tree entries are sorted the way git sorts them, which is by name except that a directory
     * compares as if its name ended in {@code /}. Getting that wrong produces a tree whose hash
     * differs from the one git would compute, and the repository fails {@code git fsck} in a way
     * that is confusing to debug later.
     */
    private static String writeTree(
            ObjectStore objects, Map<String, GeneratedFile> files, Map<String, String> blobIds, String prefix) {
        record Entry(String sortKey, int mode, String name, String objectId) {}

        List<Entry> entries = new ArrayList<>();
        String childPrefix = prefix;

        for (String directory : directChildDirectories(files.keySet(), childPrefix)) {
            String id = writeTree(objects, files, blobIds, childPrefix + directory + "/");
            entries.add(new Entry(directory + "/", DIRECTORY_MODE, directory, id));
        }

        for (Map.Entry<String, GeneratedFile> file : files.entrySet()) {
            String path = file.getKey();
            if (!path.startsWith(childPrefix)) {
                continue;
            }
            String remainder = path.substring(childPrefix.length());
            if (remainder.isEmpty() || remainder.contains("/")) {
                continue;
            }
            int mode = file.getValue().executable() ? EXECUTABLE_FILE_MODE : REGULAR_FILE_MODE;
            entries.add(new Entry(remainder, mode, remainder, blobIds.get(path)));
        }

        entries.sort(Comparator.comparing(
                entry -> entry.sortKey().getBytes(StandardCharsets.UTF_8), GitSkeletonWriter::compareBytes));

        ByteArrayOutputStream body = new ByteArrayOutputStream();
        try {
            for (Entry entry : entries) {
                body.write(Integer.toOctalString(entry.mode()).getBytes(StandardCharsets.UTF_8));
                body.write(' ');
                body.write(entry.name().getBytes(StandardCharsets.UTF_8));
                body.write(0);
                body.write(HexFormat.of().parseHex(entry.objectId()));
            }
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
        return objects.write("tree", body.toByteArray());
    }

    private static List<String> directChildDirectories(Iterable<String> paths, String prefix) {
        List<String> directories = new ArrayList<>();
        for (String path : paths) {
            if (!path.startsWith(prefix)) {
                continue;
            }
            String remainder = path.substring(prefix.length());
            int slash = remainder.indexOf('/');
            if (slash > 0) {
                String directory = remainder.substring(0, slash);
                if (!directories.contains(directory)) {
                    directories.add(directory);
                }
            }
        }
        return directories;
    }

    private static byte[] commitObject(String treeId, String message) {
        String identity = "%s <%s> %d %s".formatted(AUTHOR_NAME, AUTHOR_EMAIL, COMMIT_EPOCH_SECONDS, TIMEZONE);
        String body = "tree %s\nauthor %s\ncommitter %s\n\n%s\n".formatted(treeId, identity, identity, message);
        return body.getBytes(StandardCharsets.UTF_8);
    }

    private static String config() {
        return """
                [core]
                \trepositoryformatversion = 0
                \tfilemode = true
                \tbare = false
                \tlogallrefupdates = true
                [init]
                \tdefaultBranch = %s
                """
                .formatted(BRANCH);
    }

    /**
     * The staging area, in index format version 2.
     *
     * <p>Without it git would report every file as deleted, which is a poor first impression. The
     * stat fields are left at zero: git then re-reads each file and compares it against the blob
     * hash, which is correct, costs one stat per file on the first command, and keeps the index
     * byte-identical between generations.
     */
    private static byte[] index(Map<String, GeneratedFile> files, Map<String, String> blobIds) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try {
            out.write("DIRC".getBytes(StandardCharsets.US_ASCII));
            writeInt(out, 2);
            writeInt(out, files.size());

            for (Map.Entry<String, GeneratedFile> file : files.entrySet()) {
                byte[] path = file.getKey().getBytes(StandardCharsets.UTF_8);
                if (path.length >= 0xFFF) {
                    throw new IllegalArgumentException("path too long for the index: " + file.getKey());
                }

                for (int i = 0; i < 6; i++) {
                    writeInt(out, 0); // ctime, mtime, dev, ino — deliberately zero
                }
                writeInt(out, file.getValue().executable() ? EXECUTABLE_FILE_MODE : REGULAR_FILE_MODE);
                writeInt(out, 0); // uid
                writeInt(out, 0); // gid
                writeInt(out, file.getValue().size());
                out.write(HexFormat.of().parseHex(blobIds.get(file.getKey())));
                writeShort(out, path.length);
                out.write(path);

                // NUL-terminated and padded so each entry starts on an 8-byte boundary.
                int unpadded = 62 + path.length;
                int padding = 8 - (unpadded % 8);
                out.write(new byte[padding]);
            }

            byte[] body = out.toByteArray();
            ByteArrayOutputStream withChecksum = new ByteArrayOutputStream(body.length + 20);
            withChecksum.write(body);
            withChecksum.write(sha1(body));
            return withChecksum.toByteArray();
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    private static void writeInt(ByteArrayOutputStream out, int value) {
        out.write((value >>> 24) & 0xFF);
        out.write((value >>> 16) & 0xFF);
        out.write((value >>> 8) & 0xFF);
        out.write(value & 0xFF);
    }

    private static void writeShort(ByteArrayOutputStream out, int value) {
        out.write((value >>> 8) & 0xFF);
        out.write(value & 0xFF);
    }

    private static int compareBytes(byte[] left, byte[] right) {
        int shared = Math.min(left.length, right.length);
        for (int i = 0; i < shared; i++) {
            int difference = (left[i] & 0xFF) - (right[i] & 0xFF);
            if (difference != 0) {
                return difference;
            }
        }
        return left.length - right.length;
    }

    static byte[] sha1(byte[] content) {
        try {
            return MessageDigest.getInstance("SHA-1").digest(content);
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException("SHA-1 is required by every JDK", e);
        }
    }

    /** Collects loose objects, keyed by the {@code .git/objects/ab/cdef…} path they belong at. */
    private static final class ObjectStore {

        private final Map<String, byte[]> entries = new TreeMap<>();

        String write(String type, byte[] body) {
            byte[] header = "%s %d\0".formatted(type, body.length).getBytes(StandardCharsets.UTF_8);
            byte[] object = new byte[header.length + body.length];
            System.arraycopy(header, 0, object, 0, header.length);
            System.arraycopy(body, 0, object, header.length, body.length);

            String id = HexFormat.of().formatHex(sha1(object));
            entries.put(".git/objects/%s/%s".formatted(id.substring(0, 2), id.substring(2)), zlib(object));
            return id;
        }

        Map<String, byte[]> entries() {
            return entries;
        }

        private static byte[] zlib(byte[] content) {
            Deflater deflater = new Deflater(Deflater.DEFAULT_COMPRESSION);
            try {
                deflater.setInput(content);
                deflater.finish();
                ByteArrayOutputStream compressed = new ByteArrayOutputStream(Math.max(32, content.length / 2));
                byte[] buffer = new byte[8192];
                while (!deflater.finished()) {
                    compressed.write(buffer, 0, deflater.deflate(buffer));
                }
                return compressed.toByteArray();
            } finally {
                deflater.end();
            }
        }
    }
}
