#!/bin/bash
#
# Copies the read-only project into a writable workspace and runs the build.
#
# The working directory matters here in a way it does not for the JVM image: a
# full-stack project's frontend lives under frontend/, and a standalone one's does
# too, so the cell says where to run and this obeys it.
set -euo pipefail

# Copied only into an empty workspace. A cell whose steps share a volume (§33's typed client is
# generated by the JVM build and consumed by this one) would otherwise have this step overwrite
# everything the previous one produced with the original, unbuilt project.
if [ -z "$(ls -A /work 2>/dev/null)" ]; then
  cp -a /input/. /work/
fi

if [ -n "${KITBASH_WORKING_DIRECTORY:-}" ]; then
  cd "/work/${KITBASH_WORKING_DIRECTORY}"
fi

# Installs resolve against the registry; the store is warm, not offline. A package
# that disappears upstream still breaks the cell, which is the point (§12).
pnpm config set store-dir "$PNPM_STORE_DIR"

exec "$@"
